db.execute('''
CREATE TABLE IF NOT EXISTS `comments` (
`id` bigint(20) unsigned NOT NULL,
    `state`  varchar(30)  NULL ,
    `authorfirstname`  varchar(255)  NULL ,
    `authorlastname`  varchar(255)  NULL ,
    `authordisplayname`  varchar(255)  NULL ,
    `bodyhtml`  varchar(255)  NULL ,
    `authoremail`  varchar(255)  NULL ,
    `authorwebsite`  varchar(255)  NULL ,
    `approved`  bit(1)  NULL ,
    `akismetapproved`  bit(1)  NULL ,
    `moderatorapproved`  bit(1)  NULL ,
    `akismetcheckedat`  bigint(20)  NULL ,
    `moderatedat`  bigint(20)  NULL ,
    `parentid`  bigint(20)  NULL ,
    `editingtoken`  varchar(255)  NULL ,
    `parentpermalink`  varchar(255)  NULL ,
    `captcharesponse`  varchar(255)  NULL ,
    `createdticks`  bigint(20)  NULL ,
    `authorsecret`  varchar(255)  NULL ,
    `parenttitle`  varchar(255)  NULL ,
    `contactid`  bigint(20)  NULL ,
    `approvedat`  bigint(20)  NULL ,
    `previouslyapproved`  bit(1)  NULL ,
    `notificationsregisteredat`  bigint(20)  NULL ,
    `threadsubscribe`  bit(1)  NULL ,
    `mentionsubscribe`  bit(1)  NULL ,
    `bodymarkdown`  varchar(255)  NULL ,
    `threadid`  bigint(20)  NULL ,
    `deleted`  bit(1)  NULL ,
  `row_updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `row_updated_at_key` (`row_updated_at`),
  KEY `threadid_key` (`threadid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 
''');