db.execute('''
CREATE TABLE IF NOT EXISTS `stallion_users` (
`id` bigint(20) unsigned NOT NULL,
    `displayname`  varchar(255)  NULL ,
    `email`  varchar(255)  NULL ,
    `givenname`  varchar(255)  NULL ,
    `familyname`  varchar(255)  NULL ,
    `bcryptedpassword`  varchar(255)  NULL ,
    `secret`  varchar(255)  NULL ,
    `encryptionsecret`  varchar(255)  NULL ,
    `username`  varchar(255)  NULL ,
    `aliasforid`  bigint(20)  NULL ,
    `createdat`  bigint(20)  NULL ,
    `orgid`  bigint(20)  NULL ,
    `resettoken`  varchar(255)  NULL ,
    `approved`  bit(1)  NULL ,
    `emailverified`  bit(1)  NULL ,
    `disabled`  bit(1)  NULL ,
    `timezoneid`  varchar(255)  NULL ,
    `role`  varchar(30)  NULL ,
    `honorific`  varchar(255)  NULL ,
    `optedout`  bit(1)  NULL ,
    `totallyoptedout`  bit(1)  NULL ,
    `deleted`  bit(1)  NULL ,
  `row_updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `row_updated_at_key` (`row_updated_at`),
  UNIQUE KEY `email_key` (`email`),
  UNIQUE KEY `username_key` (`username`),
  KEY `aliasforid_key` (`aliasforid`),
  KEY `orgid_key` (`orgid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 
''');